# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
matrix:
  include:
    - os: linux
      dist: trusty
      r: release
    - os: osx
      osx_image: xcode7.4
      r: release
  allow_failures:
    - os: osx
      osx_image: xcode6.4
      r: release
    - os: linux
      dist: trusty
      r: devel
    - os: osx
      osx_image: xcode7.4
      r: devel
    - os: linux
      dist: trusty
      r: oldrel
  fast_finish: true

sudo: false
cache: packages

r_github_packages:
  - jimhester/covr

r_packages:
  - Rcpp
  - RcppArmadillo
  - devtools

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9
      - gsl-bin
      - libgsl-bin
      - libgsl-dev

before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl; fi
  - | mkdir ~/.R
      cat <<EOF > ~/.R/Makevars
      CXX1X=g++-4.9
      FC=gfortran-4.9
      CXX1XSTD=-std=c++11


after_success:
  - Rscript -e 'covr::codecov(branch="0.1.6")'
